### ISSUE TITLE
Postgres Adapter?

### ISSUE THREAD

**Issue by murphyslaw2781** [Livog/Payload.3.0.Starter#1]
When I switch to Postgres - getting error but Mongo works great.  I can find where its

` //# sourceMappingURL=getTableColumnFromPath.js.map
 ⨯ node_modules\.pnpm\@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1\node_modules\@payloadcms\db-postgres\dist\queries\getTableColumnFromPath.js (442:1) @ getTableColumnFromPath
 ⨯ Internal error: APIError: Cannot find field for path at user
    at getTableColumnFromPath (./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1/node_modules/@payloadcms/db-postgres/dist/queries/getTableColumnFromPath.js:454:11)
    at parseParams (./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1/node_modules/@payloadcms/db-postgres/dist/queries/parseParams.js:61:233)
    at buildAndOrConditions (./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1/node_modules/@payloadcms/db-postgres/dist/queries/buildAndOrConditions.js:16:94)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseParams (./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1/node_modules/@payloadcms/db-postgres/dist/queries/parseParams.js:39:45)
    at async buildQuery (./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1/node_modules/@payloadcms/db-postgres/dist/queries/buildQuery.js:62:17)
    at async find (./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.19_@types+react@18.3.1_payload@3.0.0-beta.19_react@18.3.1/node_modules/@payloadcms/db-postgres/dist/find/findMany.js:27:66)
digest: "2126473019"
  440 |         }
  441 |     }
> 442 |     throw new APIError(`Cannot find field for path at ${fieldPath}`);
      | ^
  443 | };
  444 |
  445 | //# sourceMappingURL=getTableColumnFromPath.js.map`

**Comment by Livog** [comment]
@murphyslaw2781 I havn't tested this repo with postgres but should work in theroy. Looks like it could be a Payload issue, have you tested with the latest beta.30?
